apiVersion: apps/v1
kind: Deployment
metadata:
    name: ledger-alchemy-transaction-microservice-deployment
    labels:
        app: ledger-alchemy-transaction-microservice
spec:
    replicas: 2
    selector:
        matchLabels:
            app: ledger-alchemy-transaction-microservice
    template:
        metadata:
            labels:
                app: ledger-alchemy-transaction-microservice
        spec:
            containers:
                - name: ledger-alchemy-transaction-microservice-container
                  image: SJC.ocir.io/<DOCKER_OBJECT_STORAGE_NAMESPACE>/transaction-microservice:1.0.0
                  imagePullPolicy: 'Always'
                  ports:
                      - containerPort: 3200
                  env:
                      - name: DATABASE_USER
                        valueFrom:
                            secretKeyRef:
                                name: mysql-secret
                                key: master-username
                      - name: DATABASE_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: mysql-secret
                                key: master-password
            imagePullSecrets:
                - name: ocirsecret
---
apiVersion: v1
kind: Service
metadata:
    name: ledger-alchemy-transaction-microservice-service
spec:
    selector:
        app: ledger-alchemy-transaction-microservice
    type: ClusterIP
    ports:
        - protocol: TCP
          port: 80
          targetPort: 3200
